name: cadquery
channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - ipython
  - ocp=7.7.1
  - pyparsing>=2.1.9
  - sphinx=5.0.1
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - black=19.10b0
  - mypy
  - codecov
  - click=8.0.4
  - pre-commit
  - pytest
  - pytest-cov
  - ezdxf
  - ipython
  - typing_extensions
  - nptyping=2.0.1
  - nlopt
  - path
  - casadi
  - multimethod >=1.7,<2.0
  - pip
  - pip:
    - "--editable=."
    - git+https://github.com/CadQuery/OCP-stubs.git
